# Generated by Django 2.2.6 on 2022-02-17 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220217_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='post',
        ),
    ]
