# Generated by Django 2.2.16 on 2022-03-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20220308_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(
                help_text='Текст нового комментария',
                max_length=500,
                verbose_name='Текст'),
        ),
    ]
